name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker-Volume
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/scire-client:latest .

      - name: Push into Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/scire-client:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/scire-client:latest
            docker stop scire-client || true
            docker rm scire-client || true
            docker run -d --name scire-client -p 3008:80 --restart=always ${{ secrets.DOCKER_USERNAME }}/scire-client:latest
